import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
    title: "My Tickets",
    description: "Generated by create next app",
};

const Tickets = () => {
    return (
        <div>
            View Tickets
        </div>
    )
}

export default Tickets
