import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
    title: "Sell Ticket",
    description: "Generated by create next app",
};

const Seller = () => {
    return (
        <div>
            welcome seller
        </div>
    )
}

export default Seller
